### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by kr4lt** [EqualStreetNames/equalstreetnames-munich#1]
Just some suggestions on the topic of Munich streetnames and your project (which I think is a great idea btw!):
Disclaimer: I'm not a lawyer and this is not legal advice, just some things I've personally run into or found out that may also be useful to you. 
I also absolutely don't want to diminish your efforts and I realize you might already know a lot of these things, but maybe some of it is useful.
 - You reference an external wiki in the Readme. Their license sounds like it may me incompatible with OSM's, so I'd make sure this is okay (at least if you plan to use larger parts of information from that project)
 - Your effort may possibly be considered organised editing (https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines)
 - The city of Munich maintains an official list of streets named since 1996 with descriptions of who they are named after at https://www.muenchen.de/rathaus/Stadtverwaltung/Kommunalreferat/geodatenservice/strassennamen.html. Using this is probably fine (also see https://www.ris-muenchen.de/RII/RII/ris_vorlagen_dokumente.jsp?risid=2784935, Beschluss "[..] Beitritt der Landeshauptstadt München zur Community OpenStreetMap - Deutschland "). Though you could ask to be completely sure, in my experience the administration is usually very helpful when it comes to such things.
 - The Stadtarchiv München archives all the resolutions on street naming. This would be a very authoritative source and probably the "safest" option, though it's currently harder to get access to these documents due to Covid-related measures (see https://stadtarchiv.muenchen.de/scopeQuery/detail.aspx?id=263497 and https://stadtarchiv.muenchen.de/scopeQuery/detail.aspx?id=747610)
 - Sometimes it is not obvious who a street is really named after, e.g. when there are multiple famous family members / people of the same name (e.g. https://de.wikipedia.org/wiki/Max-Weber-Platz). (These cases should be rather rare, but since many OSM contributors think that no data is better than wrong data, it may be a good idea to double check for such cases)
 - Someone has collected an extensive wiki on Munich's street names at https://stadtgeschichte-muenchen.de/strassen/index.php. It may be worth reaching out to those responsible for that site to check if they'll allow usage of that information for OSM and under OSM's license.

**Comment by ynux** [comment]
Hi, thanks for your valuable input. 
    1. About the external Wiki: That is a difficult question, I'll try to find help. 
    2. It is not organized editing, yet.

Of course it would be preferrable to use official sources. We tried. However:
    1. Having only streets named since 1996 is useless because obviously biased (in terms of gender distribution)
    2. Stadtarchiv München is closed. I asked via email about one street, which was answered after one month with the offer that they can look up the resolution for that street.
As a citizen of Munich, I am disappointed with the state of open data of our Stadtarchiv.
 
About unclear name origins: We have one such case, in Laim, the Genovevaweg. I put it into a local csv rather than OSM. There is a discussion going on if in the equalstreetnames project about how to treat such local information, see https://github.com/EqualStreetNames/equalstreetnames/issues/145

About asking stadtgeschichte-muenchen, good idea, will do.

**Comment by ynux** [comment]
stadtgeschichte-muenchen gave us the permission to use their data. Organized editing got organized. Closing this.
